default: &default
  host:  localhost
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  username: deploy
  password: password

development:
  <<: *default
  database: backend_development_not_docker

test:
  <<: *default
  database: backend_development_not_docker_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

