version: '3.8'

services:
  db:
    image: postgres:12-alpine
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-admin:
    image: dpage/pgadmin4:latest
    network_mode: "host"
    environment:
      PGADMIN_LISTEN_PORT: 8081
      PGADMIN_DEFAULT_EMAIL: hcfairbanks@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json

  rails-api:
    build:
      context: ./backend
    environment:
      RAILS_ENV: development
      DB_NAME: backend_development
      DB_USERNAME: deploy
      DB_PASSWORD: password
      DB_HOSTNAME: localhost
      DB_PORT: 5432
    restart: on-failure
    command: sh -c "bundle exec rails db:drop db:create db:migrate db:seed && bundle exec rails s"
    network_mode: "host"
    volumes: # /local_dir /container_dir
      - ./backend:/backend
    depends_on:
      - db

  front-end:
    build:
      context: ./frontend
    environment:
      BASE_URL: localhost
    restart: on-failure
    command: sh -c "pnpm dev"
    network_mode: "host"
    volumes: # /local_dir /container_dir
      - ./frontend:/frontend
    depends_on:
      - rails-api


volumes:
  pgdata:


